### ISSUE TITLE
Upgrade Firebase Version

### ISSUE THREAD

**Issue by transmissions11** [donavon/use-firebase-app#1]
Hey @donavon , this set of hooks is perfect for my use case, and I'd really like to use it, but the version of Firebase you are using uses an old version of grpc that won't compile on node versions above 10. Can you please update the version?

Thanks!

**Comment by darrenbutcher** [comment]
TLDR;
**The Fix (Yarn):**
Yarn resolutions

package.json
```
"resolutions": {
   "firebase": "^7.14.2"
 }
```
See link for more info with my comment in this associated repo:
https://github.com/donavon/use-firebase-auth/issues/3#issuecomment-622199546

Hope this helps anyone else that bumps into this.

**Comment by ripern** [comment]
Here's a PR for that, https://github.com/donavon/use-firebase-app/pull/3
